// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYeoBtpCgbQR3d_6pFvwrX8i84AUqUaQ',
    appId: '1:109831802294:web:520cddab485d28b1d94517',
    messagingSenderId: '109831802294',
    projectId: 'task-manager-app-274c1',
    authDomain: 'task-manager-app-274c1.firebaseapp.com',
    storageBucket: 'task-manager-app-274c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAHZ_McjMBJG_PxX-o0MEI34DMm8LbDE',
    appId: '1:109831802294:android:ed884f13241160ecd94517',
    messagingSenderId: '109831802294',
    projectId: 'task-manager-app-274c1',
    storageBucket: 'task-manager-app-274c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Sa_glFiiBgOAEorLyimOEmCxm1R7cpQ',
    appId: '1:109831802294:ios:e6f1ce2c289c325ad94517',
    messagingSenderId: '109831802294',
    projectId: 'task-manager-app-274c1',
    storageBucket: 'task-manager-app-274c1.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Sa_glFiiBgOAEorLyimOEmCxm1R7cpQ',
    appId: '1:109831802294:ios:e6f1ce2c289c325ad94517',
    messagingSenderId: '109831802294',
    projectId: 'task-manager-app-274c1',
    storageBucket: 'task-manager-app-274c1.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYeoBtpCgbQR3d_6pFvwrX8i84AUqUaQ',
    appId: '1:109831802294:web:cec0d14c684a9527d94517',
    messagingSenderId: '109831802294',
    projectId: 'task-manager-app-274c1',
    authDomain: 'task-manager-app-274c1.firebaseapp.com',
    storageBucket: 'task-manager-app-274c1.firebasestorage.app',
  );
}
